# Numpy tutorial 1

Oliver W. Layton

CS251: Data Analysis and Visualization

Spring 2020

In [3]:
import numpy as np

## Numpy ndarray basics

### Creation from Python lists

In [2]:
# Make a numpy array from a 2D python list
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# print it
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Data type of ndarray

In [4]:
# determine data type
print('Type of array is\n', arr.dtype)

Type of array is
 int64


Type can be changed in a few ways. 

1. when creating array — (a) implicitly or (b) explicitly
2. by casting types.

In [5]:
# 1a implicitly (changing input literals)
arr = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.]])
arr.dtype

dtype('float64')

In [7]:
# 1b explicitly
arr = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=float)
print(arr)
arr.dtype

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


dtype('float64')

In [8]:
# 2. NOTE: Casting is a METHOD of the array, not a FUNCTION
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64


In [15]:
# Can also be string. be careful in your CSV parser that your "numbers"
# aren't actually strings!
arr = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=str)
print(arr)
print(arr.dtype)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
<U1


### Convert back to Python list

In [19]:
# Convert back from ndarray to Python list (2 methods)
arr1 = arr.tolist()
arr1

[['1', '2', '3'], ['4', '5', '6'], ['7', '8', '9']]

In [21]:
arr2 = np.array([1,2,3])
arr2

array([1, 2, 3])

In [22]:
list(arr2)

[1, 2, 3]

### Other ways to create ndarrays quickly

#### 1. zeros

In [23]:
z = np.zeros([3, 90])
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.

#### 2. ones

In [24]:
one = np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
# can easily make any constant array
9.5*one

array([9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5])

In [27]:
z + 10

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10

#### 3. Random values

In [31]:
# Uniform random values
np.random.random([10, 10])

array([[0.41992779, 0.65503962, 0.76910873, 0.37297834, 0.26412673,
        0.92214093, 0.49363823, 0.61706707, 0.26755646, 0.43123532],
       [0.2136818 , 0.53536916, 0.1967642 , 0.49699262, 0.0618343 ,
        0.6829504 , 0.50925798, 0.28020075, 0.13890844, 0.67365087],
       [0.79832188, 0.78931239, 0.4293307 , 0.68710885, 0.78366535,
        0.16457095, 0.47424168, 0.68397521, 0.116795  , 0.52842524],
       [0.71377988, 0.9814933 , 0.55906078, 0.74623733, 0.33564099,
        0.13854605, 0.94787187, 0.88141501, 0.38757711, 0.38201152],
       [0.40325341, 0.28516627, 0.48720122, 0.30188262, 0.53021653,
        0.75848098, 0.56933622, 0.95270244, 0.63121736, 0.70544066],
       [0.90218951, 0.08538457, 0.56121736, 0.35649412, 0.21863709,
        0.63594617, 0.05308936, 0.92160151, 0.32634932, 0.27597446],
       [0.97269403, 0.06786368, 0.81732694, 0.25591894, 0.15022304,
        0.84312496, 0.99639137, 0.642836  , 0.70298182, 0.3103597 ],
       [0.31476576, 0.34054619, 0.2155147

#### 4. Equally spaced floats in an interval

In [35]:
np.linspace(-5, 5, 3)

array([-5.,  0.,  5.])

In [3]:
np.linspace(-5, 5)

array([-5.        , -4.79591837, -4.59183673, -4.3877551 , -4.18367347,
       -3.97959184, -3.7755102 , -3.57142857, -3.36734694, -3.16326531,
       -2.95918367, -2.75510204, -2.55102041, -2.34693878, -2.14285714,
       -1.93877551, -1.73469388, -1.53061224, -1.32653061, -1.12244898,
       -0.91836735, -0.71428571, -0.51020408, -0.30612245, -0.10204082,
        0.10204082,  0.30612245,  0.51020408,  0.71428571,  0.91836735,
        1.12244898,  1.32653061,  1.53061224,  1.73469388,  1.93877551,
        2.14285714,  2.34693878,  2.55102041,  2.75510204,  2.95918367,
        3.16326531,  3.36734694,  3.57142857,  3.7755102 ,  3.97959184,
        4.18367347,  4.3877551 ,  4.59183673,  4.79591837,  5.        ])

#### 5. Equally spaced ints in an interval

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

#### 6. Identify matrix

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Check dimensions — `shape`

In [12]:
# check shape of 3D array
arr = np.ones([1, 2, 3])
arr.shape

(1, 2, 3)

In [10]:
# check number of dimensions (M)
arr = np.ones([1, 2, 3, 4, 5, 6])
arr.ndim

6

In [11]:
# Access 1st dim (#rows), 2nd dim (#cols) (Use f-string)
print(f'Number of rows/cols is {arr.shape[0]}/{arr.shape[1]}.')

Number of rows/cols is 1/2.


In [14]:
# Check number of elements total
arr = np.ones([1, 2, 3])
print(arr)
arr.size

[[[1. 1. 1.]
  [1. 1. 1.]]]


6

## Brief detour: Rapidly build python lists (list comprehension)

In [15]:
# Brief detour: In python you can replace the workflow of 
# list-building by creating an empty list and looping to append...
lst = []
for i in range(5):
    lst.append(i)
lst

[0, 1, 2, 3, 4]

In [16]:
# ...with Python list comprehensions
lst = [i for i in range(5)]
lst

[0, 1, 2, 3, 4]

In [17]:
# you can build lists using any function of i. How about i^2?
lst = [i**2 for i in range(5)]
lst

[0, 1, 4, 9, 16]

## ndarray indexing

Basic Accessing and modifying of ndarrays.

### Access and modify single elements

In [18]:
# To access elements in a multidimensional ndarray use ONE set of square brackets []
# Make a new random array
np.random.seed(0)  # ensures random numbers come up the same each time. Useful for debugging.
mat = np.random.random([5, 4])
mat

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

In [19]:
# Get the 1st element
mat[0, 0]

0.5488135039273248

In [21]:
# Modifying single values is similar
mat[0, 0] = 9
print('mat is now:\n', mat)

mat is now:
 [[9.         0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]
 [0.0202184  0.83261985 0.77815675 0.87001215]]


### Slicing: real power of numpy

Use **colon** notation for all values in a dimension

Access and modify different ranges of data along different dimensions 

Make a 3x5 random array. Access 2nd column

In [22]:
np.random.seed(0)
arr = np.random.random([3, 5])
arr

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [23]:
arr[:, 1]

array([0.71518937, 0.43758721, 0.52889492])

Access 1st row

In [24]:
arr[0, :]

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

Access last 2 columns

In [25]:
arr[:, -2:]

array([[0.54488318, 0.4236548 ],
       [0.96366276, 0.38344152],
       [0.92559664, 0.07103606]])

Access columns at indices 1-2 and in 1st row. Careful about off-by-one.

- Low range (before :) CONTAINS that index
- High range (after :) DOES NOT contain that index (i-1)

In [28]:
arr[0, 1:3]

array([0.71518937, 0.60276338])

Use slicing to assign values efficiently in batch without loops

In [29]:
arr

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [32]:
# Assign 1st row to -1s
arr[0] = -1
arr

array([[-1.        , -1.        , -1.        , -1.        , -1.        ],
       [ 0.64589411,  0.43758721,  0.891773  ,  0.96366276,  0.38344152],
       [ 0.79172504,  0.52889492,  0.56804456,  0.92559664,  0.07103606]])

In [34]:
# Assign 1st row to increasing ints
arr[0] = np.arange(len(arr[0]))
arr

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [36]:
# Multiply the 3rd row by 5 times itself and update the row
arr[2] = 5*arr[2]
arr

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 0.64589411,  0.43758721,  0.891773  ,  0.96366276,  0.38344152],
       [19.79312595, 13.22237299, 14.20111403, 23.13991596,  1.77590145]])

In [38]:
arr[2] += 5
arr

array([[  0.        ,   1.        ,   2.        ,   3.        ,
          4.        ],
       [  0.64589411,   0.43758721,   0.891773  ,   0.96366276,
          0.38344152],
       [103.96562976,  71.11186497,  76.00557014, 120.69957979,
         13.87950727]])

### What if we want to access a set of rows or columns that are not adjacent?

Can't use colon notation. Instead use `np.ix_`

In [40]:
print(arr)

[[  0.           1.           2.           3.           4.        ]
 [  0.64589411   0.43758721   0.891773     0.96366276   0.38344152]
 [103.96562976  71.11186497  76.00557014 120.69957979  13.87950727]]


Example: Say we want column indices 0, 2, 4 and all rows.

**Syntax for `np.ix_`:**
- `np.ix_` goes inside the square brackets: `arr[np.ix_(blah)]`
- Give it `M` arguments (e.g. 2 for a 2D matrix).
- Each argument is a Python list (or ndarray) of indices to take along that dimension.

In [42]:
np.arange(len(arr))

array([0, 1, 2])

In [41]:
arr[np.ix_(np.arange(len(arr)), [0, 2, 4])]

array([[  0.        ,   2.        ,   4.        ],
       [  0.64589411,   0.891773  ,   0.38344152],
       [103.96562976,  76.00557014,  13.87950727]])

## Memory

- Numpy tries to be efficient with arrays so assignment does a shallow copy. To do a deep copy, you need to use `.copy()` method

In [43]:
a = np.linspace(-1, 1, 5)
a

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [44]:
b = a
b[0] = 9
print(a)
print(b)

[ 9.  -0.5  0.   0.5  1. ]
[ 9.  -0.5  0.   0.5  1. ]


In [45]:
# fixed with .copy()
a = np.linspace(-1, 1, 5)
b = a.copy()
b[0] = 9
print(a)
print(b)

[-1.  -0.5  0.   0.5  1. ]
[ 9.  -0.5  0.   0.5  1. ]


## Apply functions over dimensions (`axes`)

- Axes are the numpy term for different ndarray dimensions. 
- Example: axis 0 are the rows, axis 1 are the columns, etc.
- We can apply functions over one or more axis super efficiently in one line of code! This is called **Vectorization** — MUCH MUCH faster than loops (stay tuned).

In [47]:
one = np.ones([5, 3])
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Sum within columns -> "collapse" across rows to get sum within each column — 5 numbers

In [52]:
res = np.sum(one, axis=0)
print(res)
print(res.shape)

[5. 5. 5.]
(3,)


Sum within rows -> "collapse" across columns to get sum within each row — 3 numbers

In [53]:
res = np.sum(one, axis=1)
print(res)
print(res.shape)

[3. 3. 3. 3. 3.]
(5,)


**Careful:** Applying a function without specifying the axis may compute across the ENTIRE ndarray.

In [54]:
np.sum(one)

15.0

**Mnemonic trick:** Applying a function along an axis eliminates that dimension from the shape. Left with remaining dimensions.

In [55]:
print(one.shape)
the_mean = np.mean(one, axis=0)
print(f'Mean across axis 0: {the_mean.shape}')

print(one.shape)
the_mean = np.mean(one, axis=1)
print(f'Mean across axis 1: {the_mean.shape}')

(5, 3)
Mean across axis 0: (3,)
(5, 3)
Mean across axis 1: (5,)


## Broadcasting

**This is the most useful numpy feature thus far! This will become your bread-and-butter!**

### Simple example: Scalars

As we saw, we can create an array of any size with any constant value WITHOUT ANY LOOPS. This is the simplest example of numpy **broadcasting** the scalar across the ndarray.

In [56]:
# Example with basic arithmetic
arr = 3*np.ones([5,5]) + 10
arr

array([[13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.]])

### Example: Subtract the minimum value of each column for the original 2D array

In [4]:
np.random.seed(0)
rand_inds = np.random.randint(low=1, high=5, size=(5, 6))
rand_inds

array([[1, 4, 2, 1, 4, 4],
       [4, 4, 2, 4, 2, 3],
       [1, 4, 3, 1, 1, 1],
       [3, 2, 3, 4, 4, 3],
       [1, 2, 2, 2, 2, 1]])

In [5]:
np.min(rand_inds, axis=0).shape

(6,)

In [6]:
# Take the min WITHIN EACH COLUMN and subtract it from rand_inds. Print shape of result
result = rand_inds - np.min(rand_inds, axis=0)
print(result)
print(result.shape)

[[0 2 0 0 3 3]
 [3 2 0 3 1 2]
 [0 2 1 0 0 0]
 [2 0 1 3 3 2]
 [0 0 0 1 1 0]]
(5, 6)


In [3]:
# separate tangent (will finish looking at this later)
the_min_1 = np.min(rand_inds, axis=0).reshape(6,1)
rand_inds - the_min_1

ValueError: operands could not be broadcast together with shapes (5,6) (6,1) 

#### What's going on??

Let's look at the shapes:

In [61]:
print(rand_inds.shape)
print(np.min(rand_inds, axis=0).shape)

(5, 6)
(6,)


Numpy is **broadcasting** the vector to operate on the 2d ndarray (**draw this out on board**):

- Numpy looks for axis shape compatibility among the different arrays.
- Numpy sees the column dimension (5, **6**) matches the min vector (**6,**)
- Numpy adds a **singleton dimension** (a "fake" leading dimension for rows). Now the min vector is treated with shape: **(1, 6)**.
- Numpy dynamically "grows" the singleton dimension to the needed shape (5). So now the min vector is treated like a (5, 6) array.
- Numpy element-wise subtracts the two arrays: (5, 6) array can be subtracted by a (5, 6) array.
- Numpy returns the result, which is a (5, 6) array!

Process is **very memory efficient**: No new memory gets allocated during broadcasting.

#### Broadcasting only adds singleton dimensions LEFTWARD to the ndarray with smaller number of dimensions.

What if we did the same thing as above, but now wanted to **subtract the minimum value in each row**?

In [70]:
print(f'rand_inds shape: {rand_inds.shape}')
print(f'min shape: {np.min(rand_inds, axis=1).shape}')

rand_inds shape: (5, 6)
min shape: (5,)


In [71]:
rand_inds - np.min(rand_inds, axis=1)

ValueError: operands could not be broadcast together with shapes (5,6) (5,) 

**Problem:** adding singleton dimensions to the LEFT could never make the shapes compatible!! For example, numpy tries: 

    rand_inds shape: (5, 6)
    min shape: (1, 5)

but that won't work! Crash...

#### Adding singleton dimensions by ourselves

We can help numpy out and add a "new axis" ourselves to make the shapes compatible with `np.newaxis`!

In [72]:
print(f'rand_inds shape: {rand_inds.shape}')
print(f'min shape: {np.min(rand_inds, axis=1).shape}')

rand_inds shape: (5, 6)
min shape: (5,)


In [73]:
np.shape(np.min(rand_inds, axis=1)[:, np.newaxis])

(5, 1)

In [76]:
print(np.shape(rand_inds - np.min(rand_inds, axis=1)[:, np.newaxis]))
rand_inds - np.min(rand_inds, axis=1)[:, np.newaxis]

(5, 6)


array([[0, 3, 1, 0, 3, 3],
       [2, 2, 0, 2, 0, 1],
       [0, 3, 2, 0, 0, 0],
       [1, 0, 1, 2, 2, 1],
       [0, 1, 1, 1, 1, 0]])

In [77]:
the_min = np.min(rand_inds, axis=1)
rand_inds - the_min[:, np.newaxis]

array([[0, 3, 1, 0, 3, 3],
       [2, 2, 0, 2, 0, 1],
       [0, 3, 2, 0, 0, 0],
       [1, 0, 1, 2, 2, 1],
       [0, 1, 1, 1, 1, 0]])

Can also make this more readable by defining a temp variable...

#### Squeeze if you need to get rid of all singleton dimensions

"Undo" a new axis / singleton dimension

In [78]:
ex = np.zeros([1, 2, 1, 3, 1, 4, 5, 1])
ex.shape

(1, 2, 1, 3, 1, 4, 5, 1)

In [79]:
np.squeeze(ex).shape

(2, 3, 4, 5)

#### Not automatically squeezing computations

As we saw above, functions like `min` over an axis eliminate that axis from the result: 

In [80]:
print(f'Min over axis 0 shape: {np.min(rand_inds, axis=0).shape}')
print(f'Min over axis 1 shape: {np.min(rand_inds, axis=1).shape}')

Min over axis 0 shape: (6,)
Min over axis 1 shape: (5,)


If we want `min` (and some other functions) to keep the singleton dimension, we can use the optional argument `keepdims=True`:

In [81]:
print(f'Min over axis 0 shape: {np.min(rand_inds, axis=1, keepdims=True).shape}')
print(f'Min over axis 1 shape: {np.min(rand_inds, axis=0, keepdims=True).shape}')

Min over axis 0 shape: (5, 1)
Min over axis 1 shape: (1, 6)


This can **help with broadcasting compatibility when performing an operation on an axis then modifying the original ndarray.** Then we don't need to manually add a new axis.

Example with subtracting the mean:

In [83]:
np.shape(np.min(rand_inds, axis=1, keepdims=True))

(5, 1)

In [84]:
rand_inds.shape

(5, 6)

In [82]:
rand_inds - np.min(rand_inds, axis=1, keepdims=True)

array([[0, 3, 1, 0, 3, 3],
       [2, 2, 0, 2, 0, 1],
       [0, 3, 2, 0, 0, 0],
       [1, 0, 1, 2, 2, 1],
       [0, 1, 1, 1, 1, 0]])

In [ ]:
# Subtract off mean along either axis
rand_inds_centered = rand_inds.copy()

## Vectorization speed vs loops

Time computation of adding 1 to a ndarray with loop vs vectorized.

In [9]:
import time

In [10]:
def timeit(fun):
    '''Just a function to time the runtime of another function'''
    def timer():
        start = time.time()
        fun()
        end = time.time()
        print(f'Took {end - start:.3} secs to run.')
    return timer


@timeit
def addOneLoop():
    '''Use for loop to add 1 to row vector'''
    longRow = np.array([i for i in range(1, 1000000)])
    for i in range(len(longRow)):
        longRow[i] = longRow[i] + 1


@timeit
def addOneVectorized():
    '''Vectorized version of adding 1 to row vector'''
    longRow = np.array([i for i in range(1, 1000000)])
    longRow = longRow + 1

In [11]:
# Dynamic typing in python makes for loops with lots of small
# operations slow
print('addOneLoop:')
addOneLoop()

# Vectorization allows Numpy to stop searching at runtime
# and use efficient pre-compiled functions to batch-process
# the computation over the matrix
print('addOneVectorized:')
addOneVectorized()

addOneLoop:
Took 0.712 secs to run.
addOneVectorized:
Took 0.169 secs to run.


## Switching around the axes of an ndarray and matrix multiplication in numpy

We can't matrix multiply the following ndarrays due to shape issues:

In [13]:
a = 3*np.ones([3, 4])
b = 2*np.ones([3, 4])

Need to pair up as

    (3, 4) x (4, 3)

OR

    (4, 3) x (3, 4)
    
Use the transpose to help out!

In [17]:
print(np.shape(a.T @ b))
a.T @ b

(4, 4)


array([[18., 18., 18., 18.],
       [18., 18., 18., 18.],
       [18., 18., 18., 18.],
       [18., 18., 18., 18.]])

In [18]:
print(np.shape(a @ b.T))
a @ b.T

(3, 3)


array([[24., 24., 24.],
       [24., 24., 24.],
       [24., 24., 24.]])

Note: Transposing a ndarray vector isn't meaningful if you don't have a singleton dimension

In [19]:
vec = np.ones(10)
vec.shape

(10,)

In [20]:
vec.T.shape

(10,)

In [21]:
vec = np.ones([10, 1])
vec.shape

(10, 1)

In [22]:
vec.T.shape

(1, 10)

### Matrix vs. element-wise multiplication

- Star (*) operator means element-wise multiplication
- Like other basic math operators, can use broadcasting (e.g. can multiply a (3,) and a (5, 3) array)

In [23]:
a.T @ b

array([[18., 18., 18., 18.],
       [18., 18., 18., 18.],
       [18., 18., 18., 18.],
       [18., 18., 18., 18.]])

In [24]:
a * b

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [26]:
a = np.ones(3)
a.shape

(3,)

In [27]:
b = np.zeros([3,3])

In [28]:
a * b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.shape(a * b)

(3, 3)